# Generated by Django 2.2.7 on 2019-11-05 16:43

from django.db import migrations, models
import social.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SocialProvider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social', models.CharField(choices=[(None, 'Select Provider'), ('google', 'Google'), ('github', 'Github'), ('sentinel', 'sentinel')], db_column='social_provider', max_length=10, unique=True)),
                ('client_id', models.CharField(max_length=1000)),
            ],
            options={
                'verbose_name': 'Social_Provider',
                'verbose_name_plural': 'Social_Providers',
            },
        ),
        migrations.CreateModel(
            name='SocialAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_id', models.CharField(max_length=1000)),
                ('isConnected', models.BooleanField(default=False)),
                ('provider', models.ForeignKey(on_delete=models.SET(social.models.get_sentinel_socialprovider), to='social.SocialProvider')),
            ],
            options={
                'verbose_name': 'Social_Account',
                'verbose_name_plural': 'Social_Accounts',
            },
        ),
    ]
