# Generated by Django 2.2.7 on 2019-11-05 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('social', '0002_auto_20191105_2013'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='socialaccount',
            name='user have one account per provider and site',
        ),
        migrations.AddField(
            model_name='socialaccount',
            name='site',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='socialaccount_site', to='sites.Site'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='socialaccount',
            constraint=models.UniqueConstraint(fields=('user', 'provider', 'site'), name='user have one account per provider and site'),
        ),
    ]
