# Generated by Django 2.2.7 on 2019-11-05 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0003_auto_20191105_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialaccount',
            name='site',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='socialaccount_site', to='sites.Site'),
        ),
    ]
