# Generated by Django 2.2.7 on 2019-11-11 15:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0004_auto_20191105_2203'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialaccount',
            name='credentials',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='socialaccount',
            name='email',
            field=models.CharField(max_length=1000, null=True, validators=[django.core.validators.EmailValidator]),
        ),
        migrations.AddField(
            model_name='socialaccount',
            name='scopes',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
