# Generated by Django 2.2.7 on 2019-11-12 23:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0005_auto_20191111_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialaccount',
            name='email',
            field=models.CharField(max_length=1000, null=True, unique=True, validators=[django.core.validators.EmailValidator]),
        ),
    ]
