# Generated by Django 2.2.7 on 2019-11-13 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0007_auto_20191113_2024'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='socialprovider',
            constraint=models.UniqueConstraint(fields=('social', 'client_id'), name='every client_id  per social is unique'),
        ),
    ]
