# Generated by Django 2.2.7 on 2019-11-16 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0008_auto_20191113_2040'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='socialaccount',
            name='every social_id  per provider is unique for every site',
        ),
        migrations.AddConstraint(
            model_name='socialaccount',
            constraint=models.UniqueConstraint(fields=('social_id', 'provider', 'site'), name='every social_id per provider is unique for every site'),
        ),
    ]
