# Generated by Django 2.2.7 on 2019-11-05 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20191105_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailuser',
            name='site',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_site', to='sites.Site'),
        ),
    ]
