# Generated by Django 2.2.7 on 2019-11-05 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20191105_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailuser',
            name='site',
            field=models.ForeignKey(db_column='site', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_site', to='sites.Site'),
        ),
    ]
