# Generated by Django 2.2.8 on 2019-12-22 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20191105_2203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailuser',
            name='username',
        ),
    ]
