# Generated by Django 2.2.8 on 2019-12-22 20:42

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_emailuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailuser',
            name='username',
            field=models.CharField(blank=True, help_text='Optional. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, null=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
        ),
    ]
